# -*- coding: utf-8 -*-
"""application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10MVPA-OiUhhh6S7ngypGXmyppRZAofiU
"""

# app.py
import streamlit as st
import pandas as pd
import numpy as np

import joblib
from io import BytesIO
from datetime import datetime

# PDF (ReportLab)
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet


st.set_page_config(page_title="🌾 Crop Recommendation", page_icon="🌾", layout="centered")
st.title("🌾 Crop Recommendation")
st.caption("Enter soil + weather values → get the best crop recommendation instantly.")

MODEL_PATH = "model.pkl"  # must be in the GitHub repo


@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)


def generate_pdf_report(inputs_dict: dict, prediction_df: pd.DataFrame) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, title="Crop Recommendation Report")
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Crop Recommendation Report", styles["Title"]))
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>User Inputs</b>", styles["Heading2"]))
    inputs_table_data = [["Feature", "Value"]] + [[k, str(v)] for k, v in inputs_dict.items()]
    t_inputs = Table(inputs_table_data, hAlign="LEFT")
    t_inputs.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t_inputs)
    story.append(Spacer(1, 14))

    story.append(Paragraph("<b>Prediction</b>", styles["Heading2"]))
    pred_data = [prediction_df.columns.tolist()] + prediction_df.astype(str).values.tolist()
    t_pred = Table(pred_data, hAlign="LEFT")
    t_pred.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t_pred)

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


# Load model once (cached)
model = load_model()

# -------- UI Inputs only --------
st.subheader("🧾 Enter Inputs")

col1, col2 = st.columns(2)
with col1:
    N = st.number_input("Nitrogen (N)", 0.0, 200.0, 50.0, 1.0)
    P = st.number_input("Phosphorus (P)", 0.0, 200.0, 50.0, 1.0)
    K = st.number_input("Potassium (K)", 0.0, 200.0, 50.0, 1.0)
    temperature = st.number_input("Temperature (°C)", -5.0, 60.0, 25.0, 0.1)

with col2:
    humidity = st.number_input("Humidity (%)", 0.0, 100.0, 60.0, 0.1)
    ph = st.number_input("pH", 0.0, 14.0, 6.5, 0.1)
    rainfall = st.number_input("Rainfall (mm)", 0.0, 500.0, 100.0, 0.1)

X_user = pd.DataFrame([[N, P, K, temperature, humidity, ph, rainfall]],
                      columns=["N", "P", "K", "temperature", "humidity", "ph", "rainfall"])

st.markdown("---")
if st.button("🌱 Predict Crop"):
    # Prediction (Top-3 if model supports probabilities)
    inputs_dict = {
        "Nitrogen (N)": N,
        "Phosphorus (P)": P,
        "Potassium (K)": K,
        "Temperature (°C)": temperature,
        "Humidity (%)": humidity,
        "pH": ph,
        "Rainfall (mm)": rainfall,
    }

    if hasattr(model, "predict_proba"):
        proba = model.predict_proba(X_user)[0]
        classes = model.classes_
        top_idx = np.argsort(proba)[::-1][:3]

        best_crop = classes[top_idx[0]]
        st.success(f"✅ Recommended crop: **{best_crop}**")

        result_df = pd.DataFrame({
            "Rank": [1, 2, 3],
            "Crop": [classes[top_idx[0]], classes[top_idx[1]], classes[top_idx[2]]],
            "Confidence (%)": [round(proba[top_idx[0]] * 100, 2),
                               round(proba[top_idx[1]] * 100, 2),
                               round(proba[top_idx[2]] * 100, 2)]
        })

        st.subheader("Results")
        st.dataframe(result_df, use_container_width=True)
        st.bar_chart(result_df.set_index("Crop")[["Confidence (%)"]])

        pdf_bytes = generate_pdf_report(inputs_dict, result_df)

    else:
        pred = model.predict(X_user)[0]
        st.success(f"✅ Recommended crop: **{pred}**")

        result_df = pd.DataFrame({"Result": ["Recommended Crop"], "Value": [str(pred)]})

        st.subheader("Results")
        st.dataframe(result_df, use_container_width=True)

        pdf_bytes = generate_pdf_report(inputs_dict, result_df)

    st.download_button(
        label="📄 Download PDF Report",
        data=pdf_bytes,
        file_name="crop_recommendation_report.pdf",
        mime="application/pdf"
    )
